[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MobileDog"
authors = [{name = "Kate", email = "Kate170604@gmail.com"}]
dynamic = ["version", "description"]
