[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MobileDog"
authors = [{name = "Galiulina Oksana", email = "oksana17.06@bk.ru"}]
dynamic = ["version", "description"]
